[program:laravel-scheduler]
process_name=%(program_name)s
command=php /var/www/dws-portal/backend/artisan schedule:work
directory=/var/www/dws-portal/backend
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-scheduler.log
