[program:laravel-scheduler]
process_name=%(program_name)s
command=php /opt/dws-portal/backend/artisan schedule:work
directory=/opt/dws-portal/backend
autostart=true
autorestart=true
user=nginx
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-scheduler.log
